### ISSUE TITLE
Description not outputted in frontend

### ISSUE THREAD

**Issue by iamswain** [marcusig/woocommerce-product-customizer#10]
Description of customizer choice items isn't being shown in the frontend of the customizer.

**Comment by marcusig** [comment]
@iamswain 
- Do you have the setting enabled?
![image](https://user-images.githubusercontent.com/11990914/98830319-8ef42480-243a-11eb-90c3-f7b7dea4287b.png)
- Could you share an URL where the issue is visible? 

Thanks

**Comment by marcusig** [comment]
Note that the choice's description is displayed using a "tooltip":
![image](https://user-images.githubusercontent.com/11990914/98835801-28263980-2441-11eb-8320-c42fee73b877.png)

It's possible to change this, so it's shown under the label, but it requires a couple of lines of PHP and of CSS.

**Comment by iamswain** [comment]
My bad. Turns out the plugin wasn't updated. Thanks for the quick replies!!
