### ISSUE TITLE
Product Configurator - Input Fields

### ISSUE THREAD

**Issue by C0d3W1thW1ngs** [marcusig/woocommerce-product-customizer#11]
I use the Woocommerce input fields plugin. The Product Configurator overwrites these and makes them not visible. I would like to have both. If this is impossible, I would like the product customizer to include the ability to have a text input box for the customer to fill in data.

**Comment by marcusig** [comment]
Hi @C0d3W1thW1ngs 
Is this the plugin you're talking about? https://wordpress.org/plugins/product-input-fields-for-woocommerce/

> The Product Configurator overwrites these and makes them not visible.
Do you mean in the product page, or in the configurator modal?

**Comment by marcusig** [comment]
I'm closing this, as there hasn't been any response.
