### ISSUE TITLE
Not working open_configurator param

### ISSUE THREAD

**Issue by mlykotom** [marcusig/woocommerce-product-customizer#20]
When user clicks on item in cart, it redirects into page `?load_config_from_cart=hash&open_configurator=1`.
The problem is (I guess), that the configurator is not shown automatically.

Is there missing something like

```php
if ( isset( $_REQUEST['open_configurator'] ) && $_REQUEST['open_configurator'] ) {
	$args['open_configurator'] = true;
}
```
around [line 248 in frontend-woocommerce.php](https://github.com/marcusig/woocommerce-product-customizer/blob/master/src/inc/frontend/frontend-woocommerce.php#L248
)

so something like
```php
if ( $saved_configuration_content = $this->get_saved_configuration_content() ) {
	$args['config']['load_config_content'] = $saved_configuration_content;
}

// added
if ( isset( $_REQUEST['open_configurator'] ) && $_REQUEST['open_configurator'] ) {
	$args['open_configurator'] = true;
}

```

Thanks

**Comment by marcusig** [comment]
@mlykotom That's true, something is missing. 
It worked in my testing because 
```
if ( isset( $_REQUEST['open_configurator'] ) && $_REQUEST['open_configurator'] ) {
	$args['open_configurator'] = true;
}
```
is handled by the Save your design add-on. 
I'll add that fix in the next release. 

Thanks for pointing out the issue!

Marc.
