### ISSUE TITLE
How can i remove configure button. 

### ISSUE THREAD

**Issue by ashu25Oct** [marcusig/woocommerce-product-customizer#21]

**Comment by marcusig** [comment]
Hi @ashu25Oct 
Could you describe your issue a bit more?

**Comment by ashu25Oct** [comment]
Yes sure, i dont need the config button on the product page. I just
directly need the customise panel.

**Comment by marcusig** [comment]
The following code will remove the button from the page.

```
if ( function_exists( 'mkl_pc' ) ) {
	remove_action( 'woocommerce_after_add_to_cart_form', [ mkl_pc( 'frontend' )->product, 'add_configure_button' ], 20);
}

```

You can also just hide the button using CSS.

If you want to show the configurator in the page, you can use the shortcode `[mkl_configurator]`. You can find the shortcode parameters here: https://wordpress.org/plugins/product-configurator-for-woocommerce/

**Comment by ashu25Oct** [comment]
Can we connect on any social media or something for better communication?

**Comment by ashu25Oct** [comment]
I am unable to get current product id to the shortcode

**Comment by marcusig** [comment]
Sorry without context I can't really help you. 
Could you describe what you're trying to do, where you're at, where you're adding the shortcode etc...?

**Comment by ashu25Oct** [comment]
I dont want that popup of inline configurator. Like on your demo page

**Comment by ashu25Oct** [comment]
![epsilon-1](https://user-images.githubusercontent.com/33539781/110129337-d9385180-7ded-11eb-93ec-9befc5bf5a45.PNG)
I want this section on this portion of my website:
![epsilon-2](https://user-images.githubusercontent.com/33539781/110129407-ef461200-7ded-11eb-88bb-6a32f44e43e8.png)

**Comment by ashu25Oct** [comment]
for each product

**Comment by ashu25Oct** [comment]
Hlw?

**Comment by marcusig** [comment]
I'll assume that you're using the shortcode `[mkl_configurator]`.

As you're on a product page, the message you're getting indicates one of two things: 
- either the page isn't a product (which it seems to be)
- either the product isn't configurable:
![image](https://user-images.githubusercontent.com/11990914/110220459-8d110e00-7ece-11eb-8c1f-a482e340fdf3.png)

If both of those are set, you might have to add the product ID in the shortcode.
Divi enables you to create a product template, and gives you access to variables, including the product ID.

**Comment by ashu25Oct** [comment]
Dude... u are not understanding my issue. Can we please have a call or
meeting?

**Comment by marcusig** [comment]
Sorry I do not do call or meetings.
Take your time to explain your issue in details, what you want to do, and I should be able to help.

**Comment by ashu25Oct** [comment]
I need functionality like this for every product...

https://dbrand.com/shop/iphone-12-pro-max-skins

**Comment by ashu25Oct** [comment]
???

**Comment by marcusig** [comment]
So according to your previous screenshot you're using Divi.
So go to Divi > Theme builder > Add a new template

![image](https://user-images.githubusercontent.com/11990914/110998400-6f88ec00-8387-11eb-852f-73f8c9aa2b94.png)

Then choose where you want to apply this template, so All products according to what you say:

![image](https://user-images.githubusercontent.com/11990914/110998626-c7275780-8387-11eb-99a9-41e5d25ea0d9.png)

Then add a Custom body.
In there, add a Code module:

![image](https://user-images.githubusercontent.com/11990914/110998859-27b69480-8388-11eb-86a2-ee106d41b9e5.png)

and add the shortcode `[mkl_configurator]`:

![image](https://user-images.githubusercontent.com/11990914/110998976-57659c80-8388-11eb-907f-39c3f4e11176.png)

YOur template will be like this:

![image](https://user-images.githubusercontent.com/11990914/110999755-89c3c980-8389-11eb-862b-33de10bf5475.png)

Save and visit a product with a configuration ready, it should have to configurator in it.

**Comment by ashu25Oct** [comment]
Yes... i have done it. But its showing give valid product id

**Comment by ashu25Oct** [comment]
[image: image.png]
i did what you told but still i am getting this configure button. I need
the editor in the same page not a redirect or popup

**Comment by ashu25Oct** [comment]
??

**Comment by ashu25Oct** [comment]
Its is still showing configure button.

**Comment by ashu25Oct** [comment]
I dont want any popup or redirections. I want the editor direcrly on
product page

**Comment by ashu25Oct** [comment]
Please help me its really urgent

**Comment by marcusig** [comment]
I did a bit of testing using Divi, and if you use both Divi in the product's page and to build a global template, it sometimes does strange / unexpected things, or doesn't update as you would expect, not sure why,

But overall the inline shortcode should be working, so I'm not sure why this isn't working for you. 

I you want, you can send me some admin credentials here: https://wc-product-configurator.com/contact
and I'll take a look.

**Comment by ashu25Oct** [comment]
Ok sure

**Comment by ashu25Oct** [comment]
I need a custom page like this:
http://demos.mklacroix.com/configurable-watch/

With configurator on the same page not in any popup or another tab.

**Comment by ashu25Oct** [comment]
I have sent the credentials to you. Please check

**Comment by marcusig** [comment]
Got them, but I can't edit the products or Divi's templates.

**Comment by ashu25Oct** [comment]
Ok i'll make u admin... then u can?

**Comment by ashu25Oct** [comment]
i have changed your role

**Comment by marcusig** [comment]
Okay, I'm taking a look now.

**Comment by marcusig** [comment]
Alright it's fixed. It wasn't working because you had left `product_id=1` in the shortcode, instead of just `[mkl_configurator]`.
You would use product_id only if you were adding the shortcode in a page which isn't a configurable product.
