### ISSUE TITLE
how to change padding of panel for different devices?

### ISSUE THREAD

**Issue by ashu25Oct** [marcusig/woocommerce-product-customizer#24]
![image](https://user-images.githubusercontent.com/33539781/117043881-67b44b00-ad2b-11eb-82c9-9e03475dfe35.png)
i want this panel as this
![image](https://user-images.githubusercontent.com/33539781/117043949-7864c100-ad2b-11eb-9a3d-3d885342feb4.png)

how can i do that?

**Comment by ashu25Oct** [comment]
hello?

**Comment by marcusig** [comment]
Hi @ashu25Oct,

Sorry, you've share screenshots of the whole page, so I don't know what "panel" you're talking about. You'll want to describe what you're looking for in more details. 

If you want to change colors, go to Appearance > Customize > Product Configurator, and change the colors to what you want.

If it's more than that, you'll probably need to find a developer who can help you personalize the appearance further. 

Also for this project, Github is used only for reporting bugs, so please ask your questions [on wordpress.org's forum instead](https://wordpress.org/support/plugin/product-configurator-for-woocommerce/).
