### ISSUE TITLE
Another plugin breaks Shortcodes

### ISSUE THREAD

**Issue by cristianvintu13** [marcusig/woocommerce-product-customizer#31]
Hi,
I installed the following plugin '[Unit Price for WooCommerce'](https://wordpress.org/plugins/unit-price-for-woocommerce/) as I need it and it's the only one that actually does what I need. 

After I activate it, it breaks all the shortcodes related to the Product Configurator plugin. Not sure why, is there a way to fix this?
I tried setting up the short code in different ways but the shortcode doesn't want to work no matter what while the 'unit price for woocommerce' plugin is active.

Is there a way I can make an actual URL to launch the configurator as opposed to the shortcode?

Thank you so much, please let me find a solution I really love your configurator, and I also bought all addons since it works really well.

**Comment by cristianvintu13** [comment]
UPDATE: I tried multiple plugins that let you set custom quantities per piece and all of them break the shortcodes.

**Comment by marcusig** [comment]
Hi Cristian,

This happens because the Shortcode is used on a page which isn't a product, so 'Unit Price for WooCommerce' gives an error for not finding the product data.

You can try to install this update, in which I added a workaround: 
[product-configurator-for-woocommerce.zip](https://github.com/marcusig/woocommerce-product-customizer/files/7275690/product-configurator-for-woocommerce.zip)

Let me know if that works.

**Comment by cristianvintu13** [comment]
Hi,
Thank you for the fast answer!

Will this however break my current active configurators? How do you recommend me to install the update without worring about breaking the current configurators?

Thank you again!

**Comment by marcusig** [comment]
> Will this however break my current active configurators?

Which version of the plugin are you currently using? This update only adds a fix for the Unit Price for WooCommerce plugin. So if you're already using the latest version, your configurators won't be affected.

In any case I'd recommend doing a backup before updating.

**Comment by cristianvintu13** [comment]
So I installed the update you sent via FTP, disabled the original configurator Plugin and activated the update you sent. Still breaks the page.

**Comment by marcusig** [comment]
Is there any specific error, in the page or in the PHP error log?

**Comment by cristianvintu13** [comment]
If I open the configurator from the product page Button, the configurator launches even if the 'Unit Price' plugin is active. Is there a way I can implement the same button without a shortcode on another page?

`Is there any specific error, in the page or in the PHP error log?`
Not sure how to check that.

The page that breaks has the configurator shortcodes, is made with Elementor and the 'Edit with Elementor' button disappears as well as all the elementor functions from the page when it breaks.

I'm 100% sure it's the configurator shortcodes as when I remove them from the page it works.

![image](https://user-images.githubusercontent.com/65169785/135853588-7c6b9df6-14c1-4e78-8484-d6ec2e457688.png)

**Comment by marcusig** [comment]
Which shortcode are you using? [mkl_configurator_button] or [mkl_configurator]?

**Comment by cristianvintu13** [comment]
> 
> 
> Which shortcode are you using? [mkl_configurator_button] or [mkl_configurator]?

I tried both, even the 'dynamic' shortcode you guided someone on the Wordpress forum using elementor.

**Comment by marcusig** [comment]
Can you try with only [mkl_configurator] on the page, as I haven't fixed [mkl_configurator_button] in that update. 

> Is there any specific error, in the page or in the PHP error log? Not sure how to check that.

The PHP error log is either accessible via your hosting platform, or sometimes via FTP.

**Comment by cristianvintu13** [comment]
Yes! It works! 

Could you apply the same thing for [mkl_configurator_button]?

**Comment by marcusig** [comment]
Here's the update with the fix for [mkl_configurator_button]: 
[product-configurator-for-woocommerce.zip](https://github.com/marcusig/woocommerce-product-customizer/files/7278284/product-configurator-for-woocommerce.zip)

**Comment by cristianvintu13** [comment]
Works great! Thank you so much for the support!
