### ISSUE TITLE
Price for seperate Choices in configurator is not displayed correctly

### ISSUE THREAD

**Issue by Lollimois** [marcusig/woocommerce-product-customizer#42]
Hello there, 
I have an urgent request for anyone that could help me with this problem I have with the Configurator.
The problem is that the prices in the different Groups within the Layers are not displayed the way they should,
every choice within one group takes the price of the first choice OPTICALLY, as soon as I put the configured product into the cart the price is discplayed the right way. 
We tryed to hide the price for the different choices and thought that the problem was solved, but the next one is that the price summary at the buttom of the configurator is also wrong, and is taking the prices that are displayed In the configurator, lets say the summary price in the configurator is 130,00, but then the price on the cart page is pulling the real price lets say 150,00.
This is a major problem due to the wrong price being displayed when the customer is actually pressing the button to buy the product.
I really need to fix this problem as soon as possible so if anyone can help me I am free for suggestions.

**Comment by marcusig** [comment]
Hi there,
Could you share a link to the product with the issue? 
What versions of the plugin and the Extra price add-on are you using?

**Comment by Lollimois** [comment]
The Version is 1.0.12
Link to the product (problem in every product with configurator): 
[https://azubis.vomberg.de/product/masterpool-cpl-zargen-konfigurator-duplicate-4-2/]
Login for the Frontend is: VB#2021_azubis%x%

**Comment by Lollimois** [comment]
OK I have updated the Addon and I fixed the problem,
thanks alot for the fast support this problem could have ruined my vacation plans.
