### ISSUE TITLE
Show/Hide Logic

### ISSUE THREAD

**Issue by DGspan** [marcusig/woocommerce-product-customizer#43]
Bonjour Marc.

is it possible to use the show logic without the need of hiding other options?

For example: Layer 1 choice A1/A2 and Layer 2 choice B1/B2 - Click A1 show only B1 without setting a hide logic for B2

This would be sooo much easier.

Thanks. Daniel

**Comment by marcusig** [comment]
Hi Daniel,
This isn't currently possible.

In many cases, if Layer 2 display always depend on Layer 1's selection, something like this will do:

If Layer 1  > A1 is selected
then Show Layer 2 > B1
Make condition reversible

If Layer 1  > A2 is selected
then Show Layer 2 > B2
Make condition reversible

This way B1 will only be shown if  A1 is selected, and B2 only be shown if A2 is selected. 

This is enough in many situations, without having to manually hide options. 
Though the situation could be different.

**Comment by DGspan** [comment]
This works exactly how it should. Awesome !!!
