### ISSUE TITLE
JS bug everytime i click on configure button

### ISSUE THREAD

**Issue by royakiki** [marcusig/woocommerce-product-customizer#51]
we had an error:  TypeError: Cannot read properties of undefined (reading 'open')
    at Object.PC.fe.open (product_configurator.js?ver=1649415254:210:15)
    at HTMLButtonElement.configurator_init (product_configurator.js?ver=1649415254:94:11)
    at HTMLBodyElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at HTMLBodyElement.v.handle (jquery.min.js?ver=3.6.0:2:41048)
configurator_init @ product_configurator.js?ver=1649415254:96

**Comment by marcusig** [comment]
Hi @royakiki, could you share a link of the product with the error? 
This type of error often occurs when using a minify plugin or when some scripts are defered.

**Comment by royakiki** [comment]
Hello Marc,

It seems when logging out from wp-admin, the pages are working fine.

https://minjara.com/product/beside-table/
password: 1234

Best,Roy
*Roy Akiki*
*Digital Consultant*

***@***.***
***@***.***
M: +961 3 56 54 78

Amazon Sponsored Ads Foundation Certification
DoubleClick Studio Certified by Google
Certifications : Core Studio - QA - HTML5 - Youtube Masthead - Engagement
Ads - Dynamic Creative - VPAID

**Comment by marcusig** [comment]
Sorry the password doesn't seem to work
