### ISSUE TITLE
Setup menu overlaps

### ISSUE THREAD

**Issue by djibrildivgne** [marcusig/woocommerce-product-customizer#53]
Hi @marcusig first of all I want to congratulate you and thank you for this perfect plugin.
I have some problems with the menu when I start the configuration, when I choose something the menu overlaps with all the choices.
I use the PHLOX PRO theme everything works with the plugin except the menu

Thanks very much

**Comment by marcusig** [comment]
Hi @djibrildivgne 
Could you share a link or screenshots to help me understand what you mean?

**Comment by djibrildivgne** [comment]
HI MARC, 

<img width="387" alt="Capture d’écran 2022-04-25 à 15 24 24" src="https://user-images.githubusercontent.com/104332478/165121840-d9a82528-a37a-44da-bfbb-dad6dc479a3e.png">
<img width="1431" alt="Capture d’écran 2022-04-25 à 15 23 22" src="https://user-images.githubusercontent.com/104332478/165121863-d99535b3-72a6-474d-b386-776e5141de49.png">
<img width="1438" alt="Capture d’écran 2022-04-25 à 15 23 08" src="https://user-images.githubusercontent.com/104332478/165121883-e68c0a4e-ad1f-48b5-b74a-bfe312d371b5.png">

**Comment by marcusig** [comment]
I see. You'll need a bit of CSS to fix this.
Could you share a link to the product for me to take a look? Otherwise it will be difficult to help.

**Comment by djibrildivgne** [comment]
I'm actually working on localhost so how can we do ?

**Comment by djibrildivgne** [comment]
Hello , it doesn't worked

**Comment by marcusig** [comment]
Ok. It's obviously a CSS conflict with your theme, so if you can't solve that yourself, I would need access to see what's happening.

**Comment by djibrildivgne** [comment]
Ok I see, so let me put the site online and coming back to you

**Comment by djibrildivgne** [comment]
Hello Marc, you can now check it to that url www.waffledkr.com/main-shop

**Comment by djibrildivgne** [comment]
When I open the configurator with my phone now I can't see the design but the menu is now responsive and stop overlaps
![IMG_4D65E816F1A7-1](https://user-images.githubusercontent.com/104332478/165305656-b653a6b6-8ba4-4670-8b71-48f223e91d08.jpeg)

**Comment by marcusig** [comment]
The picture doesn't work for me on desktop, but that's because the image URLs are still the localhost ones:

![image](https://user-images.githubusercontent.com/11990914/165312259-6937dbde-078b-4416-bc49-a5f2425b94da.png)

You can try to use the Image fix tool in Settings > Product configurator > Tools.

**Comment by djibrildivgne** [comment]
> The CSS I sent you before works, but there is some invalid CSS before:
> 
> ![image](https://user-images.githubusercontent.com/11990914/165311514-e0b232eb-d96a-415c-972c-ce68c4d415ca.png)

So what can I do to fix it ?

> The picture doesn't work for me on desktop, but that's because the image URLs are still the localhost ones:
> 
> ![image](https://user-images.githubusercontent.com/11990914/165312259-6937dbde-078b-4416-bc49-a5f2425b94da.png)
> 
> You can try to use the Image fix tool in Settings > Product configurator > Tools.

You can try it now the pictures are here

**Comment by djibrildivgne** [comment]
It's perfect I delete that one and all works

> The CSS I sent you before works, but there is some invalid CSS before:
> 
> ![image](https://user-images.githubusercontent.com/11990914/165311514-e0b232eb-d96a-415c-972c-ce68c4d415ca.png)
