### ISSUE TITLE
Hide all Groups

### ISSUE THREAD

**Issue by PizzukaTorph** [marcusig/woocommerce-product-customizer#60]
Hi man,
i have a problem.
In my conditional logic i need to hide all GROUPS and show just a couple of them.
there is a way?
now if I not Hide every groupt my configurator show all.
please help

**Comment by marcusig** [comment]
Hi there, 
Could you please send me your request via the premium support form https://wc-product-configurator.com/my-account/support/
And send me more details about your conditions, and if possible a link to the product.
Thanks
