### ISSUE TITLE
Multi choice addon 6.3 compatability?

### ISSUE THREAD

**Issue by dakman** [marcusig/woocommerce-product-customizer#75]
so I got the updates flowing again and reconnected but i still see this

![Screen Shot 2023-08-13 at 12 30 47 AM](https://github.com/marcusig/woocommerce-product-customizer/assets/2136346/4a922b1b-845d-46f9-91b9-1184f68d9989)

**Comment by marcusig** [comment]
I've just released a new update fixing that. 
I had already made a release just for that, but didn't actually update the "tested up to" tag!
