### ISSUE TITLE
Unable to remove option from Select or Radio form fields

### ISSUE THREAD

**Issue by jayhof** [marcusig/woocommerce-product-customizer#76]
I'm unable to remove previously saved options from forms fields "Select", "Radio" or "Checkboxes".

When I click the remove icon to the right of the option I want to remove the option is visually removed at first, after I hit save and either reload the page or switch to a different choice and then back the option I removed shows back up.

<img width="524" alt="Screenshot 2023-09-07 at 11 57 18" src="https://github.com/marcusig/woocommerce-product-customizer/assets/15269648/56a9af0d-8b04-401a-8053-0d1b81d06f7f">

**Comment by marcusig** [comment]
Thank you for the report. 
I've released a new version of the add-on (1.1.27) which should fix this issue.
