### ISSUE TITLE
Hide View configuration Link in Checkout and Emails

### ISSUE THREAD

**Issue by freshlinescreative** [marcusig/woocommerce-product-customizer#79]
Hi I'd like to remove the option to View configuration. When the link is clicked it doesn't load the configuration correctly. Since the user has all of the configuration details at that point I'd just like to remove the option to go back and change things. Can you please advise on how to do this? 

Thanks

**Comment by marcusig** [comment]
Hi there!

> When the link is clicked it doesn't load the configuration correctly.

Could you tell me more about this? What's not working?

> I'd just like to remove the option to go back and change things.

What is the context of the link you want to remove?

**Comment by freshlinescreative** [comment]
Hi Marc,

      Thanks for getting back to me. The issue is that when you click the
View Configuration button, it brings you back to the configurator but half
of the images aren't showing up. I also don't want to give the user the
option to change their selections at this point either. I just think for my
use of the builder, it will be too confusing for the end user and would
rather remove the link altogether. To my knowledge, the link appears in
four places -

   - The cart page
   - The checkout page
   - The Order Success page
   - The email confirmation page

I'd like to remove this link on each of the pages/applications. Is that
possible? If it helps here's the location of the builder on the site:
https://hiatuscampers.wpengine.com/build-your-rig/
<https://mailtrack.io/trace/link/9135dbfe050002e64d746d48358d016577d34824?url=https%3A%2F%2Fhiatuscampers.wpengine.com%2Fbuild-your-rig%2F&userId=7131005&signature=e7db191e3427afaf>

Katie


Katie Doyle

Designer

Fresh Lines Creative Co.


9043473585
***@***.***
freshlinescreative.com
<https://mailtrack.io/trace/link/27383c546d5196764cb8fb7b9e2b3e07f96f6765?url=https%3A%2F%2Ffreshlinescreative.com%2F&userId=7131005&signature=af090c7e8e8827bb>
[image: facebook]
<https://mailtrack.io/trace/link/7cd3733c5f1081df61c7a4f68e69d7df42c6c14f?url=https%3A%2F%2Fwww.facebook.com%2Ffreshlinescreative&userId=7131005&signature=e97ad41ee90cc050>
[image: linkedin]
<https://mailtrack.io/trace/link/30e52212f80815381dc17627603f39eda3b8da34?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffreshlinescreative%2F&userId=7131005&signature=50edf60c99c12b39>
[image: instagram]
<https://mailtrack.io/trace/link/f4388ae9c6ae5ab818142e6615457442de119c5e?url=https%3A%2F%2Fwww.instagram.com%2Ffreshlinescreative%2F&userId=7131005&signature=261b80c6154b398b>

**Comment by freshlinescreative** [comment]
Hi there,

     I just wanted to circle back on this and see if you have any updates
for me.

Katie


Katie Doyle

Designer

Fresh Lines Creative Co.


9043473585
***@***.***
freshlinescreative.com
<https://mailtrack.io/trace/link/40fca5212bbc6ead9453605f2beaae5ea58c8281?url=https%3A%2F%2Ffreshlinescreative.com%2F&userId=7131005&signature=21bf26a06c179217>
[image: facebook]
<https://mailtrack.io/trace/link/55545af7dae63ddcd395f185477b08939e8bd2eb?url=https%3A%2F%2Fwww.facebook.com%2Ffreshlinescreative&userId=7131005&signature=7d34575a45f3526c>
[image: linkedin]
<https://mailtrack.io/trace/link/9a7165f9b9470e1d00b4699a3201bc84542b2b0a?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffreshlinescreative%2F&userId=7131005&signature=0465213f35329caf>
[image: instagram]
<https://mailtrack.io/trace/link/5bcdafb289e4b7580d1ad8fa81772b0aa9f64de1?url=https%3A%2F%2Fwww.instagram.com%2Ffreshlinescreative%2F&userId=7131005&signature=f09960b7d196b8de>

**Comment by marcusig** [comment]
Hi Katie,

There is currently no easy way (such as a setting) to hide the view/edit links.
It can be done using hooks:

Remove "Edit configuration" link:

```php
add_filter( 'mkl_pc_user_can_edit_item_from_cart', '__return_false' );
```

Remove "View configuration" link:

```php
add_action( 'init', function() {
	remove_action( 'woocommerce_order_item_meta_end', array( mkl_pc( 'frontend' )->order, 'add_view_link' ), 20 );
} );
```

I might add settings for these, but at the moment that's the only way to safely remove them.

Marc

**Comment by freshlinescreative** [comment]
That worked great, thanks for your help!

Katie


Katie Doyle

Designer

Fresh Lines Creative Co.


9043473585
***@***.***
freshlinescreative.com
<https://mailtrack.io/trace/link/e4a36bbb773b246633ffcfa844966e455a4423b5?url=https%3A%2F%2Ffreshlinescreative.com%2F&userId=7131005&signature=0c65bd91d658d4c5>
[image: facebook]
<https://mailtrack.io/trace/link/4d3aeff6909b40f40cc52d0bb86e6189bcaed609?url=https%3A%2F%2Fwww.facebook.com%2Ffreshlinescreative&userId=7131005&signature=e352ab0921cdda63>
[image: linkedin]
<https://mailtrack.io/trace/link/525993f3d7fbae6a6e0837aafca8e14fd2301094?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffreshlinescreative%2F&userId=7131005&signature=2e8ecaf54b5de6db>
[image: instagram]
<https://mailtrack.io/trace/link/8088247cfa2c501ea4bac81261176b2aeb5c1f71?url=https%3A%2F%2Fwww.instagram.com%2Ffreshlinescreative%2F&userId=7131005&signature=ae8214bba74a762f>

**Comment by freshlinescreative** [comment]
Hi Marc,

      I had one more question. The configurator reset button goes to a
certain view when clicked. Is there a way to designate which view it goes
to?

Katie


Katie Doyle

Designer

Fresh Lines Creative Co.


9043473585
***@***.***
freshlinescreative.com
[image: facebook] <https://www.facebook.com/freshlinescreative>
[image: linkedin] <https://www.linkedin.com/company/freshlinescreative/>
[image: instagram] <https://www.instagram.com/freshlinescreative/>
