### ISSUE TITLE
Cache constantly flushed

### ISSUE THREAD

**Issue by redmerrollema** [marcusig/woocommerce-product-customizer#83]
We use Redis Object Caching. And since a few weeks we see that the cache is constantly flushed by the plugin.
This is a example line in the log file: /wp-content/plugins/product-configurator-for-woocommerce/inc/db.php(226): wp_cache_flush()

This happens every minute.

Hope you can help me out.

**Comment by marcusig** [comment]
Hi @redmerrollema 
This code is run when the configurator data is saved. 
If you are using the Linked product add-on, some of the data is synched asynchronously using the Action Scheduler. 

Do you have the linked product add-on? 
If so, do you have many linked products?
Does the flushing never stop?

**Comment by redmerrollema** [comment]
Hi Marc,

The only add-ons we use are:

  *   Conditional logic
  *   Extra price
  *   Advanced description
  *   Stock management

The cache flushing does not stop. It returns every x minutes.

The following lines are in the log:

  *   /wp-content/plugins/product-configurator-for-woocommerce/inc/db.php(226): wp_cache_flush()
  *   /wp-content/plugins/woocommerce-mkl-pc-stock-management/inc/plugin.php(228): MKL\PC\DB->set('110238', '110238', 'content', Array, Array)

Hope you can help me out

Met vriendelijke groet,

[signature_2023748481]
Redmer Rollema
Kapitein & Stuurman
[Afbeelding met tekst, tafelgerei, serviesgoed, bord  Automatisch gegenereerde beschrijving]
0529 76 4444<tel:0529%2076%204444>
[signature_1007998759]
***@***.******@***.***>
[signature_429364265]
www.rollemamedia.nl<https://www.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>
[signature_1006357970]
Hessenweg West 5E-2, 7731 EC, Ommen

Let op: tussen kerst en oud en nieuw is ons kantoor gesloten. Van 5 t/m 12 januari ben ik op vakantie

Check hier de status van onze servers<https://status.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>
Leer alles over je website op onze kennisbank<https://kennisbank.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>

Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Rollema Media staat door de elektronische verzending van dit bericht niet in voor de juiste en volledige overbrenging van de inhoud, noch voor tijdige ontvangst daarvan.


Van: Marc ***@***.***>
Datum: donderdag, 21 december 2023 om 10:15
Aan: marcusig/woocommerce-product-customizer ***@***.***>
CC: Redmer | Rollema Media ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [marcusig/woocommerce-product-customizer] Cache constantly flushed (Issue #83)

Hi @redmerrollema<https://github.com/redmerrollema>
This code is run when the configurator data is saved.
If you are using the Linked product add-on, some of the data is synched asynchronously using the Action Scheduler.

Do you have the linked product add-on?
If so, do you have many linked products?
Does the flushing never stop?

**Comment by marcusig** [comment]
> The only add-ons we use are:
>  *   Conditional logic
>  *   Extra price
>  *   Advanced description
>  *   Stock management

Yes the Stock management is the one I'm talking about (linked products).
Are there many choices in your configurator which are linked to products in the shop?
Could you check the scheduled actions in WooCommerce > Status > Scheduled Actions? 
What are the statistics at the top?

![image](https://github.com/marcusig/woocommerce-product-customizer/assets/11990914/152d1c22-3a3f-4198-8d1c-2b6f3a2b034d)

**Comment by redmerrollema** [comment]
Hi Marc,

Thanks for your reply.
See printscreen for statistics.

The only process that is pending is “profitmetrics_run_feed_pr_offset”.

Met vriendelijke groet,

[signature_2023748481]
Redmer Rollema
Kapitein & Stuurman
[Afbeelding met tekst, tafelgerei, serviesgoed, bord  Automatisch gegenereerde beschrijving]
0529 76 4444<tel:0529%2076%204444>
[signature_1007998759]
***@***.******@***.***>
[signature_429364265]
www.rollemamedia.nl<https://www.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>
[signature_1006357970]
Hessenweg West 5E-2, 7731 EC, Ommen

Let op: tussen kerst en oud en nieuw is ons kantoor gesloten. Van 5 t/m 12 januari ben ik op vakantie

Check hier de status van onze servers<https://status.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>
Leer alles over je website op onze kennisbank<https://kennisbank.rollemamedia.nl/?utm_source=email&utm_medium=handtekening&utm_campaign=signature>

Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Rollema Media staat door de elektronische verzending van dit bericht niet in voor de juiste en volledige overbrenging van de inhoud, noch voor tijdige ontvangst daarvan.


Van: Marc ***@***.***>
Datum: donderdag, 21 december 2023 om 12:50
Aan: marcusig/woocommerce-product-customizer ***@***.***>
CC: Redmer | Rollema Media ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [marcusig/woocommerce-product-customizer] Cache constantly flushed (Issue #83)

The only add-ons we use are:

  *   Conditional logic
  *   Extra price
  *   Advanced description
  *   Stock management

Yes the Stock management is the one I'm talking about (linked products).
Are there many choices in your configurator which are linked to products in the shop?
Could you check the scheduled actions in WooCommerce > Status > Scheduled Actions?
What are the statistics at the top?

image.png (view on web)<https://github.com/marcusig/woocommerce-product-customizer/assets/11990914/152d1c22-3a3f-4198-8d1c-2b6f3a2b034d>

**Comment by marcusig** [comment]
Sorry attachments sent by email don't get posted on Github, so I did't see the screenshot.
It is difficult for me to say what could be the cause without having access to the site and files. 
As mentioned above, this should only be triggered when saving a configurable product which has choices with linked products, or when updating one of these linked products.
