### ISSUE TITLE
Extra price addon problem : price doesn't synchronise when the layer and the product are linked

### ISSUE THREAD

**Issue by erygy** [marcusig/woocommerce-product-customizer#89]
Hello guys,

I have ordered two add-ons: 
- Extra price
- Stock management and linked products

I have a big problem (bug): when I link a layer with a product and I want to display the price in the configurator, the latter is not up to date (e.g.: the price of the layer's product is normally 10 euros and in fact it displays 0 euros in the configurator). 
![image](https://github.com/marcusig/woocommerce-product-customizer/assets/74180109/f5ae78a6-855d-4a3c-b5f1-cecd9bdd429d)
![image](https://github.com/marcusig/woocommerce-product-customizer/assets/74180109/28f90764-2bed-425d-8c4b-7907f9b5f939)

Of course, I've linked the layer to the right product via "Stock management and linked products", so it should work normally. 
![image](https://github.com/marcusig/woocommerce-product-customizer/assets/74180109/f27c65fb-936b-45ca-8ac0-81cff860da7d)

Here's what I did to make sure it wasn't just a cache problem:
- I tested on different devices and in private browsing
- I emptied the cash of my wordpress site as well as that of my browsers

Could you please help me?

Thanks guys !

**Comment by marcusig** [comment]
Hi there, I have responded to your other request.
